### ISSUE TITLE
tcs docker image, "(ModuleNotFoundError: No module named 'tcs' )" 

### ISSUE THREAD

**Issue by B1-Rabjerg** [thecloudsphere/service#8]
Docker image tcs:latest does not run, with a generic ModuleNotFoundError.

This impacts the following containers in a tcs deployment.
``` 
api
beat
flower
```

Screenshot:
![Screenshot_20230330_161257](https://user-images.githubusercontent.com/40353739/228864417-d82f4143-d268-4ebf-9859-f866ed40375c.png)
![Screenshot_20230330_161453](https://user-images.githubusercontent.com/40353739/228864866-69b72633-7bf3-4c1d-bc7e-5cec49d610d7.png)

**Comment by berendt** [comment]
We are working on it. It is necessary to separate the worker from the control services. The worker cannot run in the Kubernetes cluster as planned because it needs direct access to docker/containerd to run the environments. The transition is more complex than expected and still takes time.

**Comment by berendt** [comment]
Container image fixed.

Please use the docker-compose environment for the moment. We're still refactoring the services to be able to run API/control services @ Kubernetes and only the worker services @ Docker Compose.

At the moment it is only possible to run API/control services as well as the worker service @ Docker Compose.

We already moved the worker service into a dedicated Docker compose environment.

Documentation available at https://thecloudsphere.io/docs/on-premise.
